global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CleanArchitecture.Domain.Entities.Products;
global using FluentValidation;
global using CleanArchitecture.Application.JwtOptions;
global using CleanArchitecture.Application.Exceptions;